CREATE TABLE TBL_MEMBER(
ID NUMBER(5) PRIMARY KEY,
PW VARCHAR(10) NOT NULL,
NAME VARCHAR(10) NOT NULL,
REG_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;

CREATE TABLE TBL_EXIT_MEMBER(
EXIT_ID NUMBER(5),
NAME VARCHAR(10),
EXIT_DATE DATE 
);

SELECT * FROM TBL_EXIT_MEMBER;

CREATE OR REPLACE TRIGGER TRG_MEMBER_EXIT
AFTER DELETE ON TBL_MEMBER
FOR EACH ROW
BEGIN
INSERT INTO TBL_EXIT_MEMBER(EXIT_ID, NAME, EXIT_DATE)
VALUES (:old.ID, :old.NAME, SYSDATE);
END;
/

SELECT * FROM TBL_MEMBER;

SELECT * FROM TBL_EXIT_MEMBER;